# Generated by Django 2.2.8 on 2019-12-17 00:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyBlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mytitle', models.CharField(max_length=200)),
                ('mytext', models.TextField()),
                ('yourcreateddate', models.DateTimeField(default=datetime.datetime(2019, 12, 17, 0, 2, 38, 90002, tzinfo=utc))),
                ('thepublishdate', models.DateTimeField(blank=True, null=True)),
                ('myauthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
